artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/summarizer-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation 
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train", "test", "validation"]

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/samsum_dataset
  tokenizer_name: facebook/bart-large-cnn

model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/samsum_dataset
  model_path: SoumyaRanjanBhoi/facebook_text_model
  metric_file_name: artifacts/model_evaluation/metric.csv

model_translation:
  root_dir : artifcats/model_translation
  tokenizer_path: SoumyaRanjanBhoi/translate_model
  model_path: SoumyaRanjanBhoi/translate_model
